databases:
  - name: mydb
    plan: free
    region: oregon

services:
  - type: web
    name: my-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: mongodb+srv://jsnikhil00:g9z2pSLv0rbUlXgB@cluster0.rr0gv7a.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
        fromDatabase:
          name: mydb
          property: connectionString
